from pygame.image import load
from os.path import join
def joinpro(file):
    return join('asserts','images',file)
chessboard=load(joinpro('Chinese-chess-board.png'))
bsoiders=load(joinpro('001.png'))
bcannos=load(joinpro('002.png'))
bhorses=load(joinpro('003.png'))
bchariots=load(joinpro('004.png'))
belephants=load(joinpro('005.png'))
badvisors=load(joinpro('006.png'))
bgeneral=load(joinpro('007.png'))
rsoiders=load(joinpro('008.png'))
rcannos=load(joinpro('009.png'))
rhorses=load(joinpro('010.png'))
rchariots=load(joinpro('011.png'))
relephants=load(joinpro('012.png'))
radvisors=load(joinpro('013.png'))
rgeneral=load(joinpro('014.png'))
preon=load(joinpro('hint.png'))
